import { Option } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "../../utils/api";

export default function PollPage() {
  const router = useRouter();
  const { id } = router.query;
  const { data, isLoading, isError, error } = api.poll.getOne.useQuery({
    id: id as string,
  });
  if (isLoading) {
    return <div>Loading...</div>;
  } else if (isError) {
    return <div>Error: {error.message}</div>;
  }
  return (
    <>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen w-full max-w-2xl flex-col items-center justify-center gap-4">
        <div className="flex w-full flex-col">
          <h1 className="text-center text-4xl font-bold">{data?.title}</h1>
          <p className="mt-4 text-center text-neutral-700">
            {data?.description}
          </p>
        </div>
        <section className="flex w-full flex-col gap-2">
          {data?.options.map((option) => (
            <Option key={option.id} option={option} />
          ))}
        </section>
      </main>
    </>
  );
}

const Option = ({ option }: { option: Option }) => {
  return (
    <div className="w-full rounded-lg border border-neutral-300 bg-white p-6 transition-all duration-150 ease-in-out hover:border-neutral-400 hover:bg-neutral-100">
      <h1 className="text-xl font-bold text-neutral-900">{option.title}</h1>
    </div>
  );
};
